# Generated by Django 3.2.8 on 2022-05-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee_leave',
            old_name='data',
            new_name='date',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
